export const images = [
  { id: 1,  image: 'Floki_wg0yhf',                  name: 'floki' },
  { id: 2,  image: 'Black_Widow_umep4p',            name: 'black widow' },
  { id: 3,  image: 'Cat_Butterfly_v2wdwt',          name: 'cat butterfly' },
  { id: 4,  image: 'Lagertha_iqj5dz',               name: 'lagertha' },
  { id: 5,  image: 'Daryl_Dixon_hb3uiz',            name: 'daryl dixon' },
  { id: 6,  image: 'Daenerys_Targaryen_bvnarg',     name: 'daenerys targaryen' },
  { id: 7,  image: 'Tommy_Shelby_ntxzu6',           name: 'tommy shelby' },
  { id: 8,  image: 'Harry_Potter_dylqip',           name: 'harry potter' },
  { id: 9,  image: 'Billie_Eilish_qvx0sd',          name: 'billie eilish' },
  { id: 10, image: 'The_Weeknd_ja6z6c',             name: 'the weeknd' },
  { id: 11, image: 'Hermione_Granger_q8t4is',       name: 'hermione granger' },
  { id: 12, image: 'Jack_Sparrow_new_zdacfy',       name: 'jack sparrow' },
  { id: 13, image: 'Harley_Quinn_iypnn6',           name: 'harley quinn' },
  { id: 14, image: 'Breaking_Bad_hyqry4',           name: 'breaking bad' },
  { id: 15, image: 'Layne_Staley_envuae',           name: 'layne staley' },
  { id: 16, image: 'Ragnar_Lothbrok_dexdrc',        name: 'ragnar lothbrok' },
  { id: 17, image: 'Severus_Snape_otcl8r',          name: 'severus snape' },
  { id: 18, image: 'Shingeki_No_Kyojin_pyzemg',     name: 'shingeki no kyojin' },
  { id: 19, image: 'Kurt_Cobain_gux3yn',            name: 'kurt cobain' },
  { id: 20, image: 'Tyler_Durden_tb4ksp',           name: 'tyler durden' },
  { id: 21, image: 'Venom_obebek',                  name: 'venom' },
]
