TRUNCATE TABLE products RESTART IDENTITY CASCADE;

INSERT INTO products (name, image, store_link, ig_link) VALUES
  ('arthur shelby',        'Arthur_Shelby_rjcpgj',            'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('aquaman',              'Aquaman_ldgbh7',                  'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('venom',                'Venom_obebek',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('alexandra daddario',   'Alexandra_Daddario_hdzvln',       'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('tyler durden',         'Tyler_Durden_tb4ksp',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('tupac',                'Tupac_lvteuz',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('tupac',                'Tupac_bnzqix',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('the weeknd',           'The_Weeknd_ja6z6c',               'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('tommy shelby',         'Tommy_Shelby_ntxzu6',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('soularouge',           'Soularouge_szqsbp',               'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('shingeki no kyojin',   'Shingeki_No_Kyojin_pyzemg',       'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('snow leopard',         'Snow_Leopard_d6qkp8',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('rust cohle',           'Rust_Cohle_zfapce',               'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('severus snape',        'Severus_Snape_otcl8r',            'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('rick grimes',          'Rick_Grimes_fkotsi',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('rick deckard',         'Rick_Deckard_t4muvt',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('rick and morty',       'Rick_and_Morty_snbknr',           'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('negan',                'Negan_vjd0bu',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('ragnar lothbrok',      'Ragnar_Lothbrok_dexdrc',          'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('king ragnar lothbrok', 'Ragnar_Lothbrok_k8kfkc',     'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('mr robot',             'Mr_Robot_bo6x5n',                 'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('kurt cobain',          'Kurt_Cobain_gux3yn',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('marilyn monroe',       'Marilyn_Monroe_q9tjap',           'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('lionel messi',         'Lionel_Messi_vj3bpk',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('layne staley',         'Layne_Staley_envuae',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('lagertha',             'Lagertha_iqj5dz',                 'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('john wick',            'John_Wick_pvlezn',                'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('kendrick lamar',       'Kendrick_Lamar_dsba87',           'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('juice wrld',           'Juice_Wrld_h0qw1u',               'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('joker heath ledger',   'Joker_Heath_Ledger_qhjxv0',       'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('joker joaquin phoenix','Joker_Joaquin_Phoenix_i1oxdx',    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('john shelby',          'John_Shelby_pgdkkm',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('jack sparrow',         'Jack_Sparrow_new_zdacfy',         'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('jack sparrow',         'Jack_Sparrow_old_rmbanb',         'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('jaime lannister',      'Jaime_Lannister_v8gfcz',          'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('ivar the boneless',    'Ivar_The_Boneless_egp7qz',        'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('hermione granger',     'Hermione_Granger_q8t4is',         'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('harry potter',         'Harry_Potter_dylqip',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('harley quinn',         'Harley_Quinn_iypnn6',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('guts',                 'Guts_uqdrir',                     'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('geralt of rivia',      'Geralt_of_Rivia_h4hyqn',          'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('gata cattana',         'Gata_Cattana_abbzgo',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('floki',                'Floki_wg0yhf',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('fezco',                'Fezco_r10mxk',                    'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('emma watson',          'Emma_Watson_oxloef',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('eminem',               'Eminem_qbj09l',                   'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('daryl dixon',          'Daryl_Dixon_hb3uiz',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('daenerys targaryen',   'Daenerys_Targaryen_bvnarg',       'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('charles aznavour',     'Charles_Aznavour_dzbnqp',         'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('chester bennington',   'Chester_Bennington_d6rthr',       'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('breaking bad',         'Breaking_Bad_hyqry4',             'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('cat butterfly',        'Cat_Butterfly_v2wdwt',            'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('black widow',          'Black_Widow_umep4p',              'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('bizarrap',             'Bizarrap_zkzly4',                 'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/'),
  ('billie eilish',        'Billie_Eilish_qvx0sd',            'https://www.etsy.com/shop/ASA7URSHOP', 'https://www.instagram.com/byasa7ur/');
